### PR TITLE
Small fixes - progress + code format

### PR DESCRIPTION
**Pull request by tpoisot**

### CODE REVIEW

**Comment by tpoisot** [comment]
@kiristern you can check that this still runs, the progressbar should be ok

**Comment by kiristern** [comment]
runs on my side, with progress bar too. However, figures have been updated and are not exactly the same as our originals

**Comment by tpoisot** [comment]
Probably because there's a random component to it - we may want to set a seed

**Comment by kiristern** [comment]
We have already set seeds to ensure reproducibility... not sure why it changed when i checkout your branch. Will have to look into this on the weekend

**Pull request merged**
